# Use an official Python runtime as a parent image
FROM python:3.6.4-stretch


# Set the working directory to /app
RUN mkdir /ml_evaluate_service
WORKDIR /ml_evaluate_service

# Install any needed packages specified in requirements.txt
ADD ml_evaluate_service/requirements.txt /ml_evaluate_service
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the current directory contents into the container at /app
ADD ./ml_evaluate_service /ml_evaluate_service

# Make port 80 available to the world outside this container
EXPOSE 8888

# ADD run_evaluate.sh /run_evaluate.sh
# ADD run_notebook.sh /run_notebook.sh

RUN chmod +x run_evaluate.sh run_notebook.sh

# launch
CMD ./run_evaluate.sh
